### ISSUE TITLE
Enforcing "\n"

### ISSUE THREAD

**Issue by bzkdjc** [jhuckaby/pixl-json-stream#2]
Hi, 
I'm writing an app that uses your excellent lib. 
Yet my app cannot communicate with the server sending JSONs just because of **`1-char '\n'`** as separator. Here, the server  will only send and listen for **`2-char '\r\n'`** between JSONs within stream. 
_I forked this to make quick changes as I needed it to work asap._

The issue here IMHO: **hardcoded `'\n'`**.

**Comment by jhuckaby** [comment]
I do apologize, I had no idea anyone would be using this module on any non-Unix platforms (where everything is “\n”).  This was an oversight on my part, and I am sorry.  I will make the EOL configurable in the next release.
- Joe

Joseph Huckaby
jhuckaby@gmail.com

**Comment by jhuckaby** [comment]
Fixed in v1.0.3: https://github.com/jhuckaby/pixl-json-stream/commit/9cb45afb0517d393c6b268d6f7fc015565071500

**Comment by bzkdjc** [comment]
Thank you very much!

**Comment by jhuckaby** [comment]
Thanks for the bug report!

**Comment by bzkdjc** [comment]
Starred!
